package tools.pki.gbay.errors;

public enum GlobalErrorCode {
	TOKEN_NOT_DETECTED, ENTITY_INCORRECT_FORMAT, KEY_NOT_FOUND, CERT_INVALID_ALGORITHM, CERT_INVALID_FORMAT, FILE_IO_ERROR, KEY_INVALID, KEY_PROVIDER_NOT_FOUND, ENTITY_INVALID_LENGTH, CERT_INVALID_SIGNATURE, FILE_NOT_FOUND, CERT_NOT_FOUND, CERT_ISSUER_NOT_SET, CERT_CRL_NOT_SET, CERT_ISSUER_NOT_FOUND, CERT_CRL_NOT_FOUND, SIG_INVALID, SIG_NOT_FOUND, CERT_INVALID_PADDING, PIN_INCORRECT, TOKEN_ERR_LOAD_LIBRARY, TOKEN_NOT_INSIDE, REQ_PARAMETER_FAILED, REQ_METHOD_NOT_ALLOWED, TXN_SUCCESS, PIN_INVALID_LENGTH, TOKEN_OPERATION_CANCEL, TOKEN_INVALID_SLOT, TXN_FAIL, PIN_INVALID_FORMAT, TOKEN_INVALID_LOGIN_TYPE, PIN_LOCKED, TOKEN_INVALID_SESSION_ID, REQ_LOGIN_NEEDED, PIN_NEEDED, TOKEN_PKI_NOTINITIALISE, REQ_ALREADY_LOGED_IN, TOKEN_GET_ATTRIBUTE_FAIL

}
